name: Auto Track Issue
on:
  issues:
    types: [labeled]

jobs:
  auto_track_issue:
    # run only if repo is not a fork
    if: github.repository == 'codinasion/codinasion' && github.event.action == 'labeled' && github.event.label.name == 'auto-track'

    runs-on: ubuntu-latest

    env:
      NUMBER: ${{ github.event.issue.number }}
      TITLE: ${{ github.event.issue.title }}
      BODY: ${{ github.event.issue.body }}

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Issue data
        run: |
          echo "Issue number : $NUMBER"
          echo "Issue title  : $TITLE"
          echo "Issue body   : $BODY"

      - name: Track Issue
        uses: ./action/
        with:
          AUTO_TRACK_ISSUE_NUMBER: ${{ env.NUMBER }}
          AUTO_TRACK_ISSUE_TITLE: ${{ env.TITLE }}
          AUTO_TRACK_ISSUE_BODY: ${{ env.BODY }}

          # Trigger
          TRIGGER_AUTO_TRACK_ISSUE: true

          # Secrets
          GITHUB_TOKEN: ${{ secrets.CODINASION_REPO_TOKEN }}
