name: Collect Tools Data

on:
  schedule:
    - cron: "17 0 * * *"
  workflow_dispatch:
    inputs:
      TEST:
        description: "This is a test ?"
        required: true
        type: boolean
        default: false
      RUNNER:
        type: choice
        description: "Action Runner"
        default: "self-hosted"
        required: true
        options:
          - "ubuntu-latest"
          - "self-hosted"

jobs:
  collect-tools-data:
    name: Collect Tools Data

    runs-on: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.RUNNER == 'ubuntu-latest' && 'ubuntu-latest' || 'self-hosted' }}

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Collect Tools Data
        id: collect-tools-data
        uses: ./action/
        with:
          TEST: ${{ inputs.TEST || 'false' }}

          # Trigger
          TRIGGER_COLLECT_TOOLS_DATA: true

          # Secrets
          GITHUB_TOKEN: ${{ secrets.CODINASION_GITHUB_TOKEN }}

      - name: Get Time
        if: github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && github.event.inputs.TEST == 'false')
        id: time
        uses: nanzm/get-time-action@master
        with:
          timeZone: UTC+5.5
          format: "YYYY-MM-DD-HH-mm-ss"

      - name: Commit Tools Data
        if: github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && github.event.inputs.TEST == 'false')
        uses: crazy-max/ghaction-github-pages@v3.0.0
        with:
          target_branch: "tools-data"
          build_dir: tools-data
          keep_history: false
          committer: Harsh Raj <harshraj8843@users.noreply.github.com>
          author: Harsh Raj <harshraj8843@users.noreply.github.com>
          commit_message: |
            Collect Tools Data - ${{ steps.time.outputs.time }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
