name: Tweet Quote Data

on:
  schedule:
    - cron: "23 0/1 * * *"
  workflow_dispatch:
    inputs:
      TEST:
        description: "This is a test ?"
        required: true
        type: boolean
        default: false

jobs:
  tweet-quote-data:
    # run only if repo is not a fork
    if: github.repository == 'codinasion/codinasion'

    name: Tweet Quote Data

    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Tweet Quote Data
        id: tweet-quote-data
        uses: ./action/
        with:
          TEST: ${{ inputs.TEST || 'false' }}

          # Trigger
          TRIGGER_TWEET_QUOTE_DATA: true

          # Secrets
          GITHUB_TOKEN: ${{ secrets.CODINASION_GITHUB_TOKEN }}
          TWITTER_APP_KEY: ${{ secrets.TWITTER_APP_KEY }}
          TWITTER_APP_SECRET: ${{ secrets.TWITTER_APP_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
